version: "3"
networks:
  default:
    name: eil

services:
  postgres:
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_EIL_DATABASE}
    ports:
      - ${PORT_DB}:5432
    volumes:
      - ${PG_VOLUME_PATH:-./postgres}:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ${EIL_DB_INIT_SCRIPT_PATH:-./init-eil-database.sh}:/docker-entrypoint-initdb.d/init-database.sh

  postgres-sso:
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_KC_DATABASE}
    ports:
      - ${PORT_DB_SSO}:5432
    volumes:
      - ${PG_SSO_VOLUME_PATH:-./postgres}:/var/lib/postgresql/data
      # - ${KC_DB_INIT_SCRIPT_PATH:-./init-kc-database.sh}:/docker-entrypoint-initdb.d/init-database.sh
      - ./sql/keycloak_db.sql:/docker-entrypoint-initdb.d/keycloak_db.sql

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@etenlab.com
      PGADMIN_DEFAULT_PASSWORD: asdfasdf
    ports:
      - ${PORT_PGADMIN}:80
    depends_on:
      - postgres

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    restart: on-failure
    # volumes: 
    #  - ./import/realm-showcase.json:/opt/keycloak/data/import/realm.json #${KC_IMPORT_REALM_PATH:-./ealm-showcase.json}:/tmp/realm-showcase.json
    environment:
      KC_DB: postgres
      KC_DB_USERNAME: ${DB_USERNAME}
      KC_DB_PASSWORD: ${DB_PASSWORD}
      KC_DB_SCHEMA: public
      KC_DB_URL_DATABASE: ${DB_KC_DATABASE}
      KC_DB_URL_HOST: postgres-sso
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
    #JDBC_PARAMS: "ssl=true"
    ports:
      - ${PORT_KEYCLOAK}:8080
    command:
      - start-dev # --features admin-fine-grained-authz && import --file  /tmp/import/realm-showcase.json
      - --features admin-fine-grained-authz
      # - --import-realm
    depends_on:
      - postgres-sso
  
  cpg-server:
    image: etenlab/cpg-server:latest
    restart: always
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_EIL_DATABASE}
      RUN_MIGRATIONS: ${RUN_MIGRATIONS}
      AWS_S3_REGION: ${AWS_S3_REGION}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      AWS_S3_ACCESS_ID: ${AWS_S3_ACCESS_ID}
      AWS_S3_SECRET_KEY: ${AWS_S3_SECRET_KEY}
      MAX_FILE_SIZE: ${MAX_FILE_SIZE}
      MAX_FILES: ${MAX_FILES}
      MODE: DEV
      PORT: 80
      CORS_ALLOW_ORIGINS: ${CORS_ALLOW_ORIGINS}
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      JWT_KEY: ${JWT_KEY}
      FRONTEND_URL: ${FRONTEND_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      FROM_EMAIL_ADDRESS: ${FROM_EMAIL_ADDRESS}
    ports:
      - ${PORT_CPG_SERVER}:80
    depends_on:
      - postgres
