---
version: '2'
networks:
  par_net:
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/16

services:
  postgres_1:
    image: postgres
    networks:
      par_net:
        ipv4_address: 10.1.1.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: asdfasdf
      POSTGRES_DB: eil_db_1
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    networks:
      par_net:
        ipv4_address: 10.1.1.4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@etenlab.com
      PGADMIN_DEFAULT_PASSWORD: asdfasdf
    ports:
      - 8104:80
    depends_on:
      - postgres_1

  zookeeper0:
    image: confluentinc/cp-zookeeper:5.2.4
    networks:
      par_net:
        ipv4_address: 10.1.1.5
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 8105
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 8105:8105

  zookeeper1:
    image: confluentinc/cp-zookeeper:5.2.4
    networks:
      par_net:
        ipv4_address: 10.1.1.6
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 8106
      ZOOKEEPER_TICK_TIME: 2000
    ports: 
      - 8106:8106

  kafka0:
    image: confluentinc/cp-kafka:5.3.1
    networks:
      par_net:
        ipv4_address: 10.1.1.7
    restart: always
    depends_on:
      - zookeeper0
    ports:
      - 8107:8107
      - 9997:9997
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper0:8105
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka0:29092,PLAINTEXT_HOST://localhost:8107
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      JMX_PORT: 9997
      KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka0 -Dcom.sun.management.jmxremote.rmi.port=9997

  kafka1:
    image: confluentinc/cp-kafka:5.3.1
    networks:
      par_net:
        ipv4_address: 10.1.1.8
    restart: always
    depends_on:
      - zookeeper1
    ports:
      - 8108:8108
      - 9998:9998
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:8106
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:29092,PLAINTEXT_HOST://localhost:8108
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      JMX_PORT: 9998
      KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka1 -Dcom.sun.management.jmxremote.rmi.port=9998

  schemaregistry0:
    image: confluentinc/cp-schema-registry:5.5.0
    networks:
      par_net:
        ipv4_address: 10.1.1.9
    restart: always
    ports:
      - 8109:8109
    depends_on:
      - zookeeper0
      - kafka0
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka0:29092
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper0:8105
      SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: PLAINTEXT
      SCHEMA_REGISTRY_HOST_NAME: schemaregistry0
      SCHEMA_REGISTRY_LISTENERS: http://schemaregistry0:8109
      SCHEMA_REGISTRY_SCHEMA_REGISTRY_INTER_INSTANCE_PROTOCOL: "http"
      SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL: INFO
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC: _schemas

  schemaregistry1:
    image: confluentinc/cp-schema-registry:5.5.0
    networks:
      par_net:
        ipv4_address: 10.1.1.10
    restart: always
    ports:
      - 8110:8110
    depends_on:
      - zookeeper1
      - kafka1
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka1:29092
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper1:8106
      SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: PLAINTEXT
      SCHEMA_REGISTRY_HOST_NAME: schemaregistry1
      SCHEMA_REGISTRY_LISTENERS: http://schemaregistry1:8110
      SCHEMA_REGISTRY_SCHEMA_REGISTRY_INTER_INSTANCE_PROTOCOL: "http"
      SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL: INFO
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC: _schemas

  kafka-connect0:
    image: confluentinc/cp-kafka-connect:6.0.1
    networks:
      par_net:
        ipv4_address: 10.1.1.11
    restart: always
    ports:
      - 8111:8111
    depends_on:
      - kafka0
      - schemaregistry0
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka0:29092
      CONNECT_GROUP_ID: compose-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: _connect_configs
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_TOPIC: _connect_offset
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_TOPIC: _connect_status
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://schemaregistry0:8106
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schemaregistry0:8106
      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect0
      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    networks:
      par_net:
        ipv4_address: 10.1.1.12
    restart: always
    ports:
      - 8112:8080
    depends_on:
      - zookeeper0
      - zookeeper1
      - kafka0
      - kafka1
      - schemaregistry0
      - kafka-connect0
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka0:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper0:8105
      KAFKA_CLUSTERS_0_JMXPORT: 9997
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schemaregistry0:8109
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: first
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://kafka-connect0:8111
      KAFKA_CLUSTERS_1_NAME: secondLocal
      KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS: kafka1:29092
      KAFKA_CLUSTERS_1_ZOOKEEPER: zookeeper1:8106
      KAFKA_CLUSTERS_1_JMXPORT: 9998
      KAFKA_CLUSTERS_1_SCHEMAREGISTRY: http://schemaregistry1:8110
      KAFKA_CLUSTERS_1_KAFKACONNECT_0_NAME: first
      KAFKA_CLUSTERS_1_KAFKACONNECT_0_ADDRESS: http://kafka-connect0:8111

  database-api:
    image: etenlab/database-api
    networks:
      par_net:
        ipv4_address: 10.1.1.3
    restart: always
    ports:
      - 8103:8103
    depends_on:
      - kafka-ui
      - postgres_1
    environment:
      HOSTNAME: localhost
      KAFKA_BOOTSTRAP: kafka0:29092
      DB_DOMAIN: postgres_1
      DB_USERNAME: postgres
      DB_DATABASE: eil_db_1
      DB_PASSWORD: asdfasdf

  authentication-api:
    image: etenlab/authentication-api
    networks:
      par_net:
        ipv4_address: 10.1.2.2
    restart: always
    ports:
      - 8202:8202
    depends_on:
      - database-api
    environment:
      HOSTNAME: localhost
      KAFKA_BOOTSTRAP: kafka0:29092
      DB_DOMAIN: postgres_1
      DB_USERNAME: postgres
      DB_DATABASE: eil_db_1
      DB_PASSWORD: asdfasdf
      JWT_SECRET: asdfasdf
      AWS_ACCESS_KEY_ID: asdf
      AWS_SECRET_ACCESS_KEY: asdf
      S3_URL_PREFIX: asdf

  dataset-api-iso-639-2:
    image: etenlab/iso-639-2-api
    networks:
      par_net:
        ipv4_address: 10.1.3.2
    restart: always
    ports:
      - 8302:8302
    depends_on:
      - database-api
    environment:
      HOSTNAME: localhost
      KAFKA_BOOTSTRAP: kafka0:29092
      DB_DOMAIN: postgres_1
      DB_USERNAME: postgres
      DB_DATABASE: eil_db_1
      DB_PASSWORD: asdfasdf

